name: mapvina_gl
description: A Flutter plugin for integrating MapVina Maps inside a Flutter application on Android, iOS and web platforms.
version: 1.0.0
homepage: https://mapvina.com
repository: https://github.com/mapvina/flutter-mapvina-gl
issue_tracker: https://github.com/mapvina/flutter-mapvina-gl/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  mapvina_gl_platform_interface: ^1.0.0
  mapvina_gl_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.mapvina.mapvinagl
        pluginClass: MapVinaMapsPlugin
      ios:
        pluginClass: MapVinaMapsPlugin
      web:
        default_package: mapvina_gl_web

platforms:
  android:
  ios:
  web:
