name: mapvina_gl_example
publish_to: none
description: Minimal example app for the mapvina_gl package published on pub.dev.
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  mapvina_gl:
    path: ..

dev_dependencies:
  very_good_analysis: ^10.2.0

dependency_overrides:
  mapvina_gl_platform_interface:
    path: ../../mapvina_gl_platform_interface
  mapvina_gl_web:
    path: ../../mapvina_gl_web

flutter:
  uses-material-design: true
