name: mapvina_gl_platform_interface
description: A common platform interface for the mapvina_gl plugin. This package is only intended to be used by the mapvina_gl package.
version: 0.26.1
repository: https://github.com/mapvina/flutter-mapvina-gl
issue_tracker: https://github.com/mapvina/flutter-mapvina-gl/issues
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
